# Generated by Django 4.2.4 on 2023-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_reviewrating_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
