# Generated by Django 4.2.4 on 2023-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
