# Generated by Django 4.2.4 on 2023-11-21 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notified_users',
            field=models.ManyToManyField(blank=True, related_name='notified_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
