# Generated by Django 4.2.4 on 2023-11-21 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notified_users',
            field=models.ManyToManyField(blank=True, related_name='subscribed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
