# Generated by Django 4.2.4 on 2023-11-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_discussionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_on_image', models.ImageField(upload_to='try_on_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
