# Generated by Django 4.2.4 on 2023-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_virtualtryon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_price', models.CharField(choices=[('5 TO 30', '5 to 30')], default='5 TO 30', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Filter Price',
                'verbose_name_plural': 'Filter Prices',
            },
        ),
    ]
