# Generated by Django 4.2.4 on 2023-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_filterprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterprice',
            name='filter_price',
            field=models.CharField(choices=[('5 TO 10', '5 TO 10'), ('10 TO 20', '10 TO 20')], default='5 TO 30', max_length=10, unique=True),
        ),
    ]
